#cloud-config
#
packages:
  - pip
  - nginx

write_files:
  -  path: /run/nginx/default
     owner: root:root
     permissions: "0644"
     defer: true
     content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
  
              client_max_body_size 20M;
              location / {
                  proxy_bind              $server_addr;
                  proxy_pass              http://127.0.0.1:8083;
                  proxy_set_header        Host            $http_host;
                  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header        X-Scheme        $scheme;
                  # proxy_set_header        X-Script-Name   /;  # -> this is wrong in the wiki, I'll update it
              }

          server_name _;

          }
runcmd:

  - mkdir -p /calibre
  - sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin install_dir=/calibre
  - pip install calibreweb
  - nohup cps
  - mv /run/nginx/default /etc/nginx/sites-enabled/default
  - systemctl reload nginx

