#cloud-config
#
packages:
  - pip
  - nginx
  - libegl1
  - libopengl0
  - libxcb-cursor0
  - xvfb
  - nfs-common
write_files:
  -  path: /run/nginx/default
     owner: root:root
     permissions: "0644"
     defer: true
     content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
  
              client_max_body_size 20M;
              location / {
                  proxy_bind              $server_addr;
                  proxy_pass              http://127.0.0.1:8083;
                  proxy_set_header        Host            $http_host;
                  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header        X-Scheme        $scheme;
              }

          server_name _;

          }
runcmd:

  - mkdir -p /calibre
  - mkdir -p ${efs_mount_point}
  - echo '${file_system_id}:/ ${efs_mount_point} nfs _netdev,tls 0 0' >> /etc/fstab
  - mount ${efs_mount_point}
  - wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin install_dir=/calibre
  - pip install calibreweb
  - mv /run/nginx/default /etc/nginx/sites-enabled/default
  - systemctl reload nginx
  - wget https://www.africau.edu/images/default/sample.pdf
  - xvfb-run calibredb add sample.pdf --library-path /${efs_mount_point} 
  - nohup cps 

